//auth
export const SET_LOADING_SCREEN = "SET_LOADING_SCREEN";
export const UPDATE_JWT_TOKEN = "UPDATE_JWT_TOKEN";
export const UPDATE_USER_ID = "UPDATE_USER_ID";
export const UPDATE_USER_EMAIL = "UPDATE_USER_EMAIL";
export const LOG_OUT_ACCOUNT = "LOG_OUT_ACCOUNT";

// matching
export const UPDATE_DIFFICULTY = "UPDATE_DIFFICULTY";
export const UPDATE_ROOM_ID = "UPDATE_ROOM_ID";

// collab
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const UPDATE_EXECUTION_RESULT = "UPDATE_EXECUTION_RESULT";
export const UPDATE_TAB = "UPDATE_TAB";
export const UPDATE_IS_CODE_RUNNING = "UPDATE_IS_CODE_RUNNING";
export const UPDATE_CURRENT_MODE = "UPDATE_CURRENT_MODE";
export const UPDATE_CODE = "UPDATE_CODE";
